### PR TITLE
chore: bump dep version

### PR DESCRIPTION
**Pull request by grant0417**

### CODE REVIEW

**Comment by Lucretiel** [comment]
Any specific reason you're dropping the minor/patch versions of serde?

**Comment by grant0417** [comment]
Only meant to drop the patch version, think that is more sane and recommended way by serde

**Comment by Lucretiel** [comment]
I can't imagine why they'd recommend that when they routinely introduce new functionality and APIs in patch version, in explicit violation of semver rules (eg, https://github.com/serde-rs/serde/releases/tag/v1.0.139). Patch versions often contain bug or security fixes (especially in tricky unsafe code, like in crossbeam channel), so I'd like to keep those present as well (no reason to allow a downstream lockfile to downgrade to a pre-fix version of a library)

**Comment by Lucretiel** [comment]
Thank you!

**Comment by Lucretiel** [comment]
Was there a specific reason that you wanted to increase the dependency versions here (like a specific performance fix, or bug / vulnerability you're mitigating)? I'm asking because I'm considering reverting this change to prevent unnecessary downstream churn.

**Comment by grant0417** [comment]
Every other dep that I include uses `crossbeam-channel` v0.5 besides `defer-drop`, the other deps can probably be reverted however.

**Comment by Lucretiel** [comment]
Ah, I forgot about the 0.X behavior in Cargo, good call.

**Comment by Lucretiel** [comment]
Kept the crossbeam-channel 0.5 dependency, reverted the others (and moved serde *down* to 1.0).

**Pull request merged**
